/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ltnc.nhom3.view.bill;

import com.ltnc.nhom3.entity.Bill;
import com.ltnc.nhom3.entity.BillDetail;
import com.ltnc.nhom3.entity.Customer;
import com.ltnc.nhom3.entity.Employee;
import com.ltnc.nhom3.entity.Price;
import com.ltnc.nhom3.entity.Product;
import com.ltnc.nhom3.service.BillDetailService;
import com.ltnc.nhom3.service.BillService;
import com.ltnc.nhom3.service.CustomerService;
import com.ltnc.nhom3.service.EmployeeService;
import com.ltnc.nhom3.service.ManufacturerService;
import com.ltnc.nhom3.service.PriceService;
import com.ltnc.nhom3.service.ProductService;
import com.ltnc.nhom3.utility.ConstantHelper;
import com.ltnc.nhom3.utility.IOHandler;
import com.ltnc.nhom3.view.template.SectionTemplate;
import com.ltnc.nhom3.view.frmMainWindow;
import com.ltnc.nhom3.view.template.TableCellListener;
import com.ltnc.nhom3.view.template.TableHelper;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class pnlAdd extends javax.swing.JPanel {
    
    private int customerId, totalQuantity = 0, num = 1;
    private List<Double> listSubTotals = new ArrayList<>();
    private List<Integer> listQuantities = new ArrayList<>();
    private List<Integer> listProductIds = new ArrayList<>();
            
    private double totalMoney = 0;
    private Employee employee;
    
    private EmployeeService employeeService;
    private CustomerService customerService;
    private PriceService priceService;
    private ManufacturerService manufacturerService;
    private BillService billService;
    private BillDetailService billDetailService;
    private ProductService productService;
    
    /**
     * Creates new form pnlDetail
     * @param id
     * @param productService
     */   
    public pnlAdd(EmployeeService employeeService, CustomerService customerService, PriceService priceService,
            BillService billService, BillDetailService billDetailService, ProductService productService,
            ManufacturerService manufacturerService) {
        this.employeeService = employeeService;
        this.customerService = customerService;
        this.priceService = priceService;
        this.billService = billService;
        this.manufacturerService = manufacturerService;
        this.billDetailService = billDetailService;
        this.productService = productService;
        employee = frmMainWindow.rootFrame.getLoggedInEmployee();
        
        initComponents();
        jScrollPane1.getViewport().setBackground(ConstantHelper.SECTION_PANEL_BG);
        tblProductList.getTableHeader().setReorderingAllowed(false);

        lblTotal.setText(String.format(ConstantHelper.LBL_TOTAL_ADD_BILL, totalQuantity, IOHandler.convertToDisplayPriceString(totalMoney)));
        generateInfoToForm();

        new TableCellListener(tblProductList, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                TableCellListener tcl = (TableCellListener) e.getSource();
                int row = tcl.getRow(), newQuantity = (int) tcl.getNewValue();
                double price = listSubTotals.get(row)/listQuantities.get(row);
                double newSubTotal = price*newQuantity;
                DefaultTableModel model = (DefaultTableModel) tblProductList.getModel();
                model.setValueAt(IOHandler.convertToDisplayPriceString(newSubTotal), row, tcl.getColumn()+1);
                listQuantities.set(row, newQuantity);
                listSubTotals.set(row, newSubTotal);
                refreshTotal();
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = SectionTemplate.getStyledPanel();
        lblHeading = new javax.swing.JLabel();
        btnGoBack = SectionTemplate.getStyledButton();
        jSeparator2 = SectionTemplate.getStyledSeparator();
        pnlForm = SectionTemplate.getStyledPanel();
        pnlLeft = SectionTemplate.getStyledPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        pnlRight = SectionTemplate.getStyledPanel();
        lblCreateDate = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextPane();
        txtCustomer = new javax.swing.JTextField();
        btnChooseCustomer = SectionTemplate.getStyledButton();
        txtEmployee = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductList = new TableHelper.CustomTable();
        jSeparator1 = SectionTemplate.getStyledSeparator();
        jPanel2 = SectionTemplate.getStyledPanel();
        btnReset = SectionTemplate.getStyledButton();
        btnSubmit = SectionTemplate.getStyledButton();
        btnDeleteBillDetail = SectionTemplate.getStyledButton();
        btnAddBillDetail = SectionTemplate.getStyledButton();
        lblTotal = new javax.swing.JLabel();

        setBackground(ConstantHelper.SECTION_PANEL_BG);
        setMinimumSize(new java.awt.Dimension(654, 596));
        setPreferredSize(new java.awt.Dimension(654, 596));

        lblHeading.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblHeading.setText("Tạo hóa đơn");

        btnGoBack.setText("Quay lại");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Khách hàng:");
        jLabel22.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel22.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Ngày tạo hóa đơn:");
        jLabel27.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel27.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Nhân viên tạo:");
        jLabel28.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel28.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel28.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText("Note:");
        jLabel29.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel29.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel29.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10))
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel22)
                .addGap(56, 56, 56)
                .addComponent(jLabel27)
                .addGap(20, 20, 20)
                .addComponent(jLabel28)
                .addGap(24, 24, 24)
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCreateDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCreateDate.setText("[tự động]");

        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setEnabled(false);

        txtNote.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(txtNote);

        txtCustomer.setEditable(false);
        txtCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCustomer.setName(""); // NOI18N
        txtCustomer.setPreferredSize(new java.awt.Dimension(6, 25));

        btnChooseCustomer.setText("Chọn KH");
        btnChooseCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseCustomerActionPerformed(evt);
            }
        });

        txtEmployee.setEditable(false);
        txtEmployee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmployee.setName(""); // NOI18N
        txtEmployee.setPreferredSize(new java.awt.Dimension(6, 25));

        javax.swing.GroupLayout pnlRightLayout = new javax.swing.GroupLayout(pnlRight);
        pnlRight.setLayout(pnlRightLayout);
        pnlRightLayout.setHorizontalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCreateDate)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(btnChooseCustomer)
                    .addComponent(txtCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlRightLayout.setVerticalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChooseCustomer)
                .addGap(13, 13, 13)
                .addComponent(lblCreateDate)
                .addGap(17, 17, 17)
                .addComponent(txtEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFormLayout = new javax.swing.GroupLayout(pnlForm);
        pnlForm.setLayout(pnlFormLayout);
        pnlFormLayout.setHorizontalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(pnlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(pnlRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlFormLayout.setVerticalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(333, 333, 333))
        );

        jScrollPane1.setBackground(ConstantHelper.SECTION_PANEL_BG);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblProductList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Sản phẩm", "Đơn giá", "Số lượng", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductList.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblProductList);
        if (tblProductList.getColumnModel().getColumnCount() > 0) {
            tblProductList.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGoBack))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
                                .addGap(10, 10, 10)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        btnReset.setText("Đặt lại");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSubmit.setText("Lưu");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmit)
                .addGap(2, 2, 2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnReset))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        btnDeleteBillDetail.setText("Xóa SP");
        btnDeleteBillDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBillDetailActionPerformed(evt);
            }
        });

        btnAddBillDetail.setText("Thêm SP");
        btnAddBillDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBillDetailActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotal.setText("Tổng:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddBillDetail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDeleteBillDetail)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteBillDetail)
                    .addComponent(btnAddBillDetail)
                    .addComponent(lblTotal))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        frmMainWindow.rootFrame.loadInSection(new pnlList(employeeService, customerService, priceService, billService, billDetailService, productService, manufacturerService));
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtCustomer.setText("");
        txtNote.setText("");
        totalQuantity = 0;
        totalMoney = 0;
        lblTotal.setText(String.format(ConstantHelper.LBL_TOTAL_ADD_BILL, totalQuantity, IOHandler.convertToDisplayPriceString(totalMoney)));
        ((DefaultTableModel) tblProductList.getModel()).setRowCount(0);
        listQuantities.clear();
        listSubTotals.clear();
        listProductIds.clear();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if ("".equals(txtCustomer.getText())) {
            return;
        }
        int numProduct = tblProductList.getRowCount();
        if (numProduct > 0) {
            Bill bill = new Bill();
            bill.setEmployeeId(employee.getId());
            bill.setCreateDate(IOHandler.convertToStringSQLDateTime(new Date()));
            bill.setCustomerId(customerId);
            bill.setNote(txtNote.getText());
            bill.setTotalMoney(totalMoney);
            
            try {
                int newBillId = billService.create(bill);
                if (newBillId != 0) {
                    BillDetail billDetail = null;
                    for (int i = 0; i < numProduct; i++) {
                        billDetail = new BillDetail();
                        
                        billDetail.setBillId(newBillId);
                        billDetail.setProductId(listProductIds.get(i));
                        billDetail.setQuantity(listQuantities.get(i));
                        billDetail.setSubTotal(listProductIds.get(i));
                        
                        billDetailService.create(billDetail);
                    }
                    JOptionPane.showMessageDialog(frmMainWindow.rootFrame, "Tạo hóa đơn thành công");
                    btnGoBackActionPerformed(null);
            }
            } catch (SQLException ex) {
                Logger.getLogger(pnlAdd.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnDeleteBillDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBillDetailActionPerformed
        if (tblProductList.getSelectedRowCount() > 0) {
            int[] selectedIndexes = tblProductList.getSelectedRows();
            DefaultTableModel model = (DefaultTableModel) tblProductList.getModel();
            for (int index : selectedIndexes) {
                model.removeRow(index);
                listQuantities.remove(index);
                listSubTotals.remove(index);
                listProductIds.remove(index);
            }
            refreshTotal();
        }
    }//GEN-LAST:event_btnDeleteBillDetailActionPerformed

    private void btnAddBillDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBillDetailActionPerformed
        JDialog d = new JDialog(frmMainWindow.rootFrame, true);
        com.ltnc.nhom3.view.product.pnlList list = new com.ltnc.nhom3.view.product.pnlList(priceService, 
                productService, manufacturerService, true, d);
        d.add(list);
        list.setVisible(true);
        Dimension dim = list.getPreferredSize();
        d.setMinimumSize(new Dimension(dim.width, dim.height+20));
        d.setResizable(false);
        d.setLocationRelativeTo(frmMainWindow.rootFrame);
        d.setTitle("Chọn");
        d.setVisible(true);
        
        addProductToTable(list.getReturnedProductId());
    }//GEN-LAST:event_btnAddBillDetailActionPerformed

    private void btnChooseCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseCustomerActionPerformed
        JDialog d = new JDialog(frmMainWindow.rootFrame, true);
        com.ltnc.nhom3.view.customer.pnlList list = new com.ltnc.nhom3.view.customer.pnlList(customerService, true, d);
        d.add(list);
        list.setVisible(true);
        Dimension dim = list.getPreferredSize();
        d.setMinimumSize(new Dimension(dim.width, dim.height+20));
        d.setResizable(false);
        d.setLocationRelativeTo(frmMainWindow.rootFrame);
        d.setTitle("Chọn");
        d.setVisible(true);
        customerId = list.getReturnedCustomerId();
        displayCustomerInfo();
    }//GEN-LAST:event_btnChooseCustomerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBillDetail;
    private javax.swing.JButton btnChooseCustomer;
    private javax.swing.JButton btnDeleteBillDetail;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCreateDate;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JTable tblProductList;
    private javax.swing.JTextField txtCustomer;
    private javax.swing.JTextField txtEmployee;
    private javax.swing.JTextPane txtNote;
    // End of variables declaration//GEN-END:variables

    private void generateInfoToForm() {
        txtEmployee.setText(employee.getFullname() + " ("+ employee.getUsername() +")");
    }

    private void displayCustomerInfo() {
        try {
            Customer c = customerService.findById(customerId);
            if (c != null) {
                txtCustomer.setText(c.getFullname() + " - ĐT: " + c.getPhone() + " - ĐC: " +c.getAddress());
            }
        } catch (SQLException ex) {
            Logger.getLogger(pnlAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void addProductToTable(int productId) {
        try {
            Product p = productService.findById(productId);
            Price price = priceService.findPriceByProductId(productId);
            double money = price.getValue();
            DefaultTableModel model = (DefaultTableModel) tblProductList.getModel();
            model.addRow(new Object[]{num++, p.getName(), IOHandler.convertToDisplayPriceString(money), 1, IOHandler.convertToDisplayPriceString(money * 1)});
            listSubTotals.add(money);
            listQuantities.add(1);
            listProductIds.add(productId);
            refreshTotal();
        } catch (SQLException ex) {
            Logger.getLogger(pnlAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void refreshTotal() {
        totalMoney = 0;
        totalQuantity = 0;
        for (Double d : listSubTotals) totalMoney += d;
        for (Integer i : listQuantities) totalQuantity += i;
        lblTotal.setText(String.format(ConstantHelper.LBL_TOTAL_ADD_BILL, totalQuantity, IOHandler.convertToDisplayPriceString(totalMoney)));
    }
}
