/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ltnc.nhom3.view.bill;

import com.ltnc.nhom3.entity.Bill;
import com.ltnc.nhom3.service.BillDetailService;
import com.ltnc.nhom3.service.BillService;
import com.ltnc.nhom3.service.PriceService;
import com.ltnc.nhom3.service.ProductService;
import com.ltnc.nhom3.utility.ConstantHelper;
import com.ltnc.nhom3.utility.IOHandler;
import com.ltnc.nhom3.view.template.TableHelper;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author duynn2911
 */
public
        class pnlList extends javax.swing.JPanel {
   private BillService billService;
   private BillDetailService billDetailService;
   private ProductService productService;
   private PriceService priceService;

   /**
    * Creates new form pnlList
    */
   public
           pnlList() {
              billService = new BillService();
              billDetailService = new BillDetailService();
              productService = new ProductService();
              priceService = new PriceService();
      initComponents();
      loadTable(null);
      jScrollPanel.getViewport().setBackground(Color.white);
      tblBill.getTableHeader().setReorderingAllowed(false);
      btnClearSearch.setVisible(true);
      
   }
           public void setOnOffForButton(boolean isOn)
           {
              btnDelete.setEnabled(isOn);
              btnEdit.setEnabled(isOn);
              btnDetail.setEnabled(isOn);
           }

           private
    void loadTable(List<Bill> bills)
           {
              String[] titles = ConstantHelper.TBL_PRODUCT_TITLES;
              DefaultTableModel dtm = TableHelper.getNonEditableTableModel(titles);
              if(bills == null )
                 bills = billService.findAll();
              Object[] row = new Object[titles.length];
              if(bills.isEmpty())
              {
                 row[1] = ConstantHelper.NO_RESULT_MESSAGE;
                 dtm.addRow(row);
                 setOnOffForButton(false);
              }
              else
              {
                 for(Bill bill : bills)
                 {
                    row[0] = bill.getId();
                    row[1] = bill.getCustomerId();
                    row[3] = bill.getEmployeeId();
                    row[4] = IOHandler.convertToDisplayDate(bill.getCreateDate());
                    dtm.addRow(row);
                 }
                 setOnOffForButton(true);
              }
              tblBill.setModel(dtm);
              TableHelper.setWithForAllColumns(tblBill,ConstantHelper.TBL_PRODUCT_TITLES_WIDTHS);
           }
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      btnAdd = new javax.swing.JButton();
      btnEdit = new javax.swing.JButton();
      btnDelete = new javax.swing.JButton();
      btnDetail = new javax.swing.JButton();
      jScrollPanel = new javax.swing.JScrollPane();
      tblBill = new javax.swing.JTable();
      jScrollPane1 = new javax.swing.JScrollPane();
      txtSearch = new javax.swing.JTextArea();
      btnClearSearch = new javax.swing.JButton();

      jLabel1.setText("BILL LIST");

      btnAdd.setText("Add");
      btnAdd.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAddActionPerformed(evt);
         }
      });

      btnEdit.setText("Edit");

      btnDelete.setText("Delete");

      btnDetail.setText("Detail");

      tblBill.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
         },
         new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
         }
      ));
      jScrollPanel.setViewportView(tblBill);

      txtSearch.setColumns(20);
      txtSearch.setRows(5);
      txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            txtSearchKeyPressed(evt);
         }
      });
      jScrollPane1.setViewportView(txtSearch);

      btnClearSearch.setText("Back");
      btnClearSearch.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnClearSearchActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAdd)
            .addGap(18, 18, 18)
            .addComponent(btnEdit)
            .addGap(18, 18, 18)
            .addComponent(btnDelete)
            .addGap(18, 18, 18)
            .addComponent(btnDetail)
            .addGap(47, 47, 47))
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(btnClearSearch)
                  .addGap(18, 18, 18)
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addComponent(jScrollPanel))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap(27, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnClearSearch, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(jScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnAdd)
               .addComponent(btnEdit)
               .addComponent(btnDelete)
               .addComponent(btnDetail))
            .addGap(28, 28, 28))
      );
   }// </editor-fold>//GEN-END:initComponents

   private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {                                      
        txtSearch.setForeground(ConstantHelper.SEARCH_SECTION_TEXT_FOCUS);
        if ("Tìm kiếm".equals(txtSearch.getText())) {
            txtSearch.setText("");
        }
    }                                     

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {                                    
        txtSearch.setForeground(ConstantHelper.SEARCH_SECTION_TEXT_NON_FOCUS);
        if (txtSearch.getText() == null || txtSearch.getText().length() == 0) {
            txtSearch.setText("Tìm kiếm");
        }
    }                               
   private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
      // TODO add your handling code here:
      
   }//GEN-LAST:event_btnAddActionPerformed

   private void btnClearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSearchActionPerformed
      // TODO add your handling code here:
     jLabel1.setText("Bill List");
     jLabel1.setToolTipText(null);
     txtSearch.setText("");
      loadTable(null);
      btnClearSearch.setVisible(false);
   }//GEN-LAST:event_btnClearSearchActionPerformed

   private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
      // TODO add your handling code here:
      String searchKey = txtSearch.getText();
      if(!searchKey.equals("") && evt.getKeyCode()==KeyEvent.VK_ENTER)
      {
         List<Bill> listResultBill;
         listResultBill = BillService.findAllByName(searchKey);
         loadTable(listResultBill);
         String searchKeyHeading = searchKey;
         if(searchKeyHeading.length()>20)
            searchKeyHeading = searchKeyHeading.substring(0,15)+"...";
         jLabel1.setText("List bill for key: '"+searchKeyHeading+"'");
         jLabel1.setToolTipText("List bill for key: '"+searchKey+"'");
         btnClearSearch.setVisible(true);
      }
   }//GEN-LAST:event_txtSearchKeyPressed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnAdd;
   private javax.swing.JButton btnClearSearch;
   private javax.swing.JButton btnDelete;
   private javax.swing.JButton btnDetail;
   private javax.swing.JButton btnEdit;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPanel;
   private javax.swing.JTable tblBill;
   private javax.swing.JTextArea txtSearch;
   // End of variables declaration//GEN-END:variables
}