/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.ltnc.nhom3.view;

import com.ltnc.nhom3.utility.ColorHelper;
import com.ltnc.nhom3.view.panel.product.pnlList;
import java.awt.Color;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.UIManager;

/**
 *
 * @author admin
 */
public class frmMainWindow extends javax.swing.JFrame {
    
    private JPanel pnlInSection;
    
    public static frmMainWindow rootFrame;
    
    /** Creates new form frmMainWindow */
    public frmMainWindow() {
        rootFrame = this;
        initComponents();
        UIManager.put("OptionPane.background", ColorHelper.SECTION_PANEL_BG);
        UIManager.put("Panel.background", ColorHelper.SECTION_PANEL_BG);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupBtnMenu = new javax.swing.ButtonGroup();
        pnlSection = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        pnlMenuContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnProduct = new javax.swing.JToggleButton();
        btnCustomer = new javax.swing.JToggleButton();
        btnBill = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("App nhom 3");

        pnlSection.setBackground(ColorHelper.SECTION_PANEL_BG);

        javax.swing.GroupLayout pnlSectionLayout = new javax.swing.GroupLayout(pnlSection);
        pnlSection.setLayout(pnlSectionLayout);
        pnlSectionLayout.setHorizontalGroup(
            pnlSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        pnlSectionLayout.setVerticalGroup(
            pnlSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlMenu.setBackground(ColorHelper.MENU_PANEL_BG);

        pnlMenuContainer.setBackground(pnlMenu.getBackground());

        jLabel1.setBackground(pnlMenu.getBackground());
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("App");
        jLabel1.setOpaque(true);

        jSeparator1.setBackground(ColorHelper.MENU_PANEL_LINE);
        jSeparator1.setForeground(ColorHelper.MENU_PANEL_LINE);

        btnProduct.setBackground(pnlMenu.getBackground());
        groupBtnMenu.add(btnProduct);
        btnProduct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnProduct.setText("Sản phẩm");
        btnProduct.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        btnProduct.setContentAreaFilled(false);
        btnProduct.setFocusPainted(false);
        btnProduct.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProduct.setMargin(new java.awt.Insets(2, 24, 2, 24));
        btnProduct.setOpaque(true);
        btnProduct.setPreferredSize(new java.awt.Dimension(80, 45));
        btnProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuSelectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuSelectMouseExited(evt);
            }
        });
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductActionPerformed(evt);
            }
        });

        btnCustomer.setBackground(pnlMenu.getBackground());
        groupBtnMenu.add(btnCustomer);
        btnCustomer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomer.setText("Khách hàng");
        btnCustomer.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        btnCustomer.setContentAreaFilled(false);
        btnCustomer.setFocusPainted(false);
        btnCustomer.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCustomer.setMargin(new java.awt.Insets(2, 24, 2, 24));
        btnCustomer.setOpaque(true);
        btnCustomer.setPreferredSize(new java.awt.Dimension(80, 45));
        btnCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuSelectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuSelectMouseExited(evt);
            }
        });
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        btnBill.setBackground(pnlMenu.getBackground());
        groupBtnMenu.add(btnBill);
        btnBill.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBill.setForeground(new java.awt.Color(255, 255, 255));
        btnBill.setText("Hóa đơn");
        btnBill.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        btnBill.setContentAreaFilled(false);
        btnBill.setFocusPainted(false);
        btnBill.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnBill.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBill.setMargin(new java.awt.Insets(2, 24, 2, 24));
        btnBill.setOpaque(true);
        btnBill.setPreferredSize(new java.awt.Dimension(80, 45));
        btnBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuSelectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuSelectMouseExited(evt);
            }
        });

        jLabel2.setBackground(pnlMenu.getBackground());
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nhóm 3 - LTNC 20191");
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout pnlMenuContainerLayout = new javax.swing.GroupLayout(pnlMenuContainer);
        pnlMenuContainer.setLayout(pnlMenuContainerLayout);
        pnlMenuContainerLayout.setHorizontalGroup(
            pnlMenuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMenuContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(pnlMenuContainerLayout.createSequentialGroup()
                        .addGroup(pnlMenuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 82, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMenuContainerLayout.setVerticalGroup(
            pnlMenuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuContainerLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnBill, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 421, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(pnlMenuContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnlMenuContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuSelectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuSelectMouseEntered
        JToggleButton button = (JToggleButton) evt.getComponent();
        setStyleForButton(button, ColorHelper.STT_BTN_HOVER);
    }//GEN-LAST:event_btnMenuSelectMouseEntered

    private void btnMenuSelectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuSelectMouseExited
        JToggleButton button = (JToggleButton) evt.getComponent();
        if (button.isSelected())
            setStyleForButton(button, ColorHelper.STT_BTN_SELECTED);
        else setStyleForButton(button, ColorHelper.STT_BTN_NORMAL);
    }//GEN-LAST:event_btnMenuSelectMouseExited

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        if (!(pnlInSection instanceof pnlList)){
            loadProductList();
            reloadGroupButtons();
        }    
    }//GEN-LAST:event_btnProductActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        reloadGroupButtons();
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void setStyleForButton(JToggleButton button, int status) {
        Color color = null;
        switch(status) {
            case ColorHelper.STT_BTN_SELECTED:
                color = ColorHelper.MENU_BTN_BG_SELECTED;
                break;
            case ColorHelper.STT_BTN_HOVER:
                color = ColorHelper.MENU_BTN_BG_HOVER;
                break;
            case ColorHelper.STT_BTN_NORMAL:
                color = ColorHelper.MENU_PANEL_BG;
                break;
        }
        button.setBackground(color);
    }
    
    private void reloadGroupButtons() {
        for (Enumeration<AbstractButton> buttons = groupBtnMenu.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) 
                setStyleForButton((JToggleButton) button, ColorHelper.STT_BTN_SELECTED);
            else setStyleForButton((JToggleButton) button, ColorHelper.STT_BTN_NORMAL);
        }
    }
    
    private void displayInContainer(JPanel jPanel, JPanel tab) {
        GroupLayout tabProductLayout = (GroupLayout) tab.getLayout();
        tabProductLayout.setHorizontalGroup(
                tabProductLayout.createParallelGroup(GroupLayout.Alignment.CENTER)
                        .addGroup(tabProductLayout.createSequentialGroup()
                                .addComponent(jPanel, 0, GroupLayout.PREFERRED_SIZE, Integer.MAX_VALUE)
                                )
        );
        tabProductLayout.setVerticalGroup(
                tabProductLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addGroup(tabProductLayout.createSequentialGroup()
                                .addComponent(jPanel, 0, GroupLayout.PREFERRED_SIZE, Integer.MAX_VALUE)
                                )
        );
    }
    
    public void loadProductList(){
        pnlInSection = new pnlList();
        displayInContainer(pnlInSection, pnlSection);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBill;
    private javax.swing.JToggleButton btnCustomer;
    private javax.swing.JToggleButton btnProduct;
    private javax.swing.ButtonGroup groupBtnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMenuContainer;
    private javax.swing.JPanel pnlSection;
    // End of variables declaration//GEN-END:variables

}
